// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcTRE5UEwt9KxIHxx59Bj2cFKhiF9v7u0',
    appId: '1:538016124193:web:4647e6c34d6ed95a94c260',
    messagingSenderId: '538016124193',
    projectId: 'lastexam-appdev',
    authDomain: 'lastexam-appdev.firebaseapp.com',
    storageBucket: 'lastexam-appdev.firebasestorage.app',
    measurementId: 'G-KX8FJRPDEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAGswE0MpBkZcZx0LPN0YeNqlS29F58g',
    appId: '1:538016124193:android:1adcf3b595b2cac794c260',
    messagingSenderId: '538016124193',
    projectId: 'lastexam-appdev',
    storageBucket: 'lastexam-appdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM5cnnjuZ0uzAZEwloyM16KhbbCAZ9Rh4',
    appId: '1:538016124193:ios:6cc1caafe23530ad94c260',
    messagingSenderId: '538016124193',
    projectId: 'lastexam-appdev',
    storageBucket: 'lastexam-appdev.firebasestorage.app',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM5cnnjuZ0uzAZEwloyM16KhbbCAZ9Rh4',
    appId: '1:538016124193:ios:6cc1caafe23530ad94c260',
    messagingSenderId: '538016124193',
    projectId: 'lastexam-appdev',
    storageBucket: 'lastexam-appdev.firebasestorage.app',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcTRE5UEwt9KxIHxx59Bj2cFKhiF9v7u0',
    appId: '1:538016124193:web:374d6fa05e88cc3f94c260',
    messagingSenderId: '538016124193',
    projectId: 'lastexam-appdev',
    authDomain: 'lastexam-appdev.firebaseapp.com',
    storageBucket: 'lastexam-appdev.firebasestorage.app',
    measurementId: 'G-RMZPZXJPV6',
  );

}